[package]
name = "technique"
version = "0.3.0"
edition = "2021"
description = "A domain specific lanaguage for procedures."
authors = [ "Andrew Cowie" ]
repository = "https://github.com/technique-lang/technique"
license = "MIT"

[dependencies]
clap = "4.5.16"
